import random

random_samples={
    "zips": ["77449",
            "77494",
            "11368",
            "79936",
            "90011",
            "60629",
            "75034",
            "11385",
            "77084",
            "91331",
            "90650",
            "75070",
            "11211",
            "08701",
            "90201",
            "11208",
            "10467",
            "11236",
            "11226",
            "90044",
            "92335",
            "92336",
            "37013",
            "94565",
            "90250",
            "90805",
            "92503",
            "75052",
            "60618",
            "90280",
            "91342",
            "11373",
            "77479",
            "11234",
            "00926",
            "11220",
            "10456",
            "11214",
            "10025",
            "91710",
            "30043",
            "78660",
            "92683",
            "11207",
            "78521",
            "77433",
            "77584",
            "92804",
            "60632",
            "10314",
            "11219",
            "75217",
            "30044",
            "92154",
            "77429",
            "11206",
            "92704",
            "60639",
            "77573",
            "60647",
            "29483",
            "95076",
            "93307",
            "11230",
            "92376",
            "10458",
            "91744",
            "92592",
            "94112",
            "93033",
            "93722",
            "93727",
            "79938",
            "91911",
            "11377",
            "60617",
            "11221",
            "11229",
            "78666",
            "92126",
            "60804",
            "22193",
            "92345",
            "78613",
            "91335",
            "66062",
            "10453",
            "11223",
            "92509",
            "77379",
            "60623",
            "11355",
            "91709",
            "78572",
            "00725",
            "60608",
            "27610",
            "99301",
            "94544",
            "95035",
            "60625",
            "95823",
            "11233",
            "30024",
            "10468",
            "11235",
            "77083",
            "87121",
            "79912",
            "95630",
            "78577",
            "37042",
            "47906",
            "75211",
            "93550",
            "76244",
            "78130",
            "78542",
            "28269",
            "90706",
            "91706",
            "10029",
            "93257",
            "78245",
            "33024",
            "23464",
            "11204",
            "92553",
            "11203",
            "33311",
            "37211",
            "94533",
            "10462",
            "11212",
            "75035",
            "10452",
            "63376",
            "60634",
            "10466",
            "90255",
            "91910",
            "94536",
            "10457",
            "60505",
            "94587",
            "96706",
            "30349",
            "10002",
            "92805",
            "77036",
            "85364",
            "93535",
            "80013",
            "97006",
            "19120",
            "93274",
            "89108",
            "75228",
            "33023",
            "33012",
            "90003",
            "77450",
            "92105",
            "96797",
            "33025",
            "92882",
            "76063",
            "85032",
            "11375",
            "00949",
            "30040",
            "77459",
            "33411",
            "11218",
            "91730",
            "10469",
            "94110",
            "91766",
            "97007",
            "93306",
            "28277",
            "78641",
            "91402",
            "60614",
            "93065",
            "89110",
            "84095",
            "85142",
            "84118",
            "75002",
            "45011",
            "00953",
            "10463",
            "22191",
            "33647",
            "78046",
            "60657",
            "20906",
            "34953",
            "60085",
            "77095",
            "80219",
            "90262",
            "76028",
            "73099",
            "85225",
            "19124",
            "30127",
            "98052",
            "93536",
            "92021",
            "07055",
            "34787",
            "06902",
            "60641",
            "11215",
            "20011",
            "92880",
            "97701",
            "32828",
            "80015",
            "92563",
            "97229",
            "60640",
            "80134",
            "30041",
            "92703",
            "90631",
            "95687",
            "30022",
            "90026",
            "92114",
            "87114",
            "95123",
            "28027",
            "30096",
            "33186",
            "85301",
            "30052",
            "92407",
            "11691",
            "27587",
            "30281",
            "11706",
            "21234",
            "94558",
            "75243",
            "07087",
            "75067",
            "94509",
            "19111",
            "48197",
            "10472",
            "85204",
            "11746",
            "11209",
            "20002",
            "89031",
            "60620",
            "30135",
            "90037",
            "93230",
            "94080",
            "94538",
            "33157",
            "98012",
            "78596",
            "33015",
            "11213",
            "90022",
            "95747",
            "85281",
            "77346",
            "91343",
            "85308",
            "78045",
            "30331",
            "77845",
            "92801",
            "84015",
            "92677",
            "95127",
            "10977",
            "75068",
            "37075",
            "95624",
            "30047",
            "94541",
            "23462",
            "95758",
            "30062",
            "92201",
            "43123",
            "76179",
            "30004",
            "07002",
            "94015",
            "07305",
            "10027",
            "23322",
            "30188",
            "95020",
            "85033",
            "66061",
            "91977",
            "78664",
            "11210",
            "19143",
            "90019",
            "84043",
            "93906",
            "92115",
            "94513",
            "11434",
            "11432",
            "94806",
            "92562",
            "32765",
            "60628",
            "95206",
            "17603",
            "14850",
            "84404",
            "99654",
            "32218",
            "7093",
            "83646",
            "87120",
            "20147",
            "92346",
            "20019",
            "94501",
            "43081",
            "33463",
            "44256",
            "60651",
            "11717",
            "02301",
            "08753",
            "11201",
            "44035",
            "85326",
            "00956",
            "10032",
            "27406",
            "90042",
            "89121",
            "92627",
            "89115",
            "78501",
            "43026",
            "20878",
            "90660",
            "60402",
            "92404",
            "91732",
            "91950",
            "11372",
            "33313",
            "46307",
            "90640",
            "91770",
            "43055",
            "74012",
            "78574",
            "75043",
            "28215",
            "10023",
            "95608",
            "78520",
            "75040",
            "78228",
            "85008",
            "40475",
            "95112",
            "92647",
            "78251",
            "85041",
            "94122",
            "19134",
            "91702",
            "32210",
            "78745",
            "95014",
            "95111",
            "38401",
            "21740",
            "42101",
            "32822",
            "91762",
            "78250",
            "78249",
            "93312",
            "07047",
            "10701",
            "34711",
            "60073",
            "43130",
            "77373",
            "91761",
            "10312",
            "48180",
            "33414",
            "33064",
            "32825",
            "60619",
            "33125",
            "77072",
            "20874",
            "21122",
            "28078",
            "02148",
            "60609",
            "78240",
            "29072",
            "98682",
            "92707",
            "92570",
            "33027",
            "89123",
            "75150",
            "90731",
            "75056",
            "90004",
            "37129",
            "93905",
            "78753",
            "92057",
            "76137",
            "29681",
            "06010",
            "77521",
            "44060",
            "76010",
            "29485",
            "53215",
            "77407",
            "92324",
            "75227",
            "92504",
            "95051",
            "90001",
            "02360",
            "30263",
            "30058",
            "92020",
            "02155",
            "80634",
            "96818",
            "19720",
            "85035",
            "79924",
            "95355",
            "30906",
            "11435",
            "77077",
            "10031",
            "10473",
            "90006",
            "28173",
            "30101",
            "37167",
            "73160",
            "92780",
            "10460",
            "92630",
            "32244",
            "22003",
            "77840",
            "00612",
            "29445",
            "22030",
            "21117",
            "32808",
            "60016",
            "93291",
            "27858",
            "90066",
            "92507",
            "43230",
            "78254",
            "33142",
            "29732",
            "23452",
            "37064",
            "23454",
            "33511",
            "28314",
            "22407",
            "31419",
            "78640",
            "55106",
            "72401",
            "85122",
            "95828",
            "33458",
            "22192",
            "60638",
            "00976",
            "10128"],
    "cities": ["Katy",
                "Corona",
                "El Paso",
                "Los Angeles",
                "Chicago",
                "Frisco",
                "Ridgewood",
                "Houston",
                "Pacoima",
                "Norwalk",
                "McKinney",
                "Brooklyn",
                "Lakewood",
                "Bell",
                "Brooklyn",
                "Bronx",
                "Brooklyn",
                "Brooklyn",
                "Los Angeles",
                "Fontana",
                "Fontana",
                "Antioch",
                "Pittsburg",
                "Hawthorne",
                "Long Beach",
                "Riverside",
                "Grand Prairie",
                "Chicago",
                "South Gate",
                "Sylmar",
                "Elmhurst",
                "Sugar Land",
                "Brooklyn",
                "San Juan",
                "Brooklyn",
                "Bronx",
                "Brooklyn",
                "New York City",
                "Chino",
                "Lawrenceville",
                "Pflugerville",
                "Westminster",
                "Brooklyn",
                "Brownsville",
                "Cypress",
                "Pearland",
                "Anaheim",
                "Chicago",
                "Staten Island",
                "Brooklyn",
                "Dallas",
                "Lawrenceville",
                "San Diego",
                "Cypress",
                "Brooklyn",
                "Santa Ana",
                "Chicago",
                "League City",
                "Chicago",
                "Summerville",
                "Watsonville",
                "Bakersfield",
                "Brooklyn",
                "Rialto",
                "Bronx",
                "La Puente",
                "Temecula",
                "San Francisco",
                "Oxnard",
                "Fresno",
                "Fresno",
                "El Paso",
                "Chula Vista",
                "Woodside",
                "Chicago",
                "Brooklyn",
                "Brooklyn",
                "San Marcos",
                "San Diego",
                "Cicero",
                "Woodbridge",
                "Hesperia",
                "Cedar Park",
                "Reseda",
                "Olathe",
                "Bronx",
                "Brooklyn",
                "Riverside",
                "Spring",
                "Chicago",
                "Flushing",
                "Chino Hills",
                "Mission",
                "Caguas",
                "Chicago",
                "Raleigh",
                "Pasco",
                "Hayward",
                "Milpitas",
                "Chicago",
                "Sacramento",
                "Brooklyn",
                "Suwanee",
                "Bronx",
                "Brooklyn",
                "Houston",
                "Albuquerque",
                "El Paso",
                "Folsom",
                "Pharr",
                "Clarksville",
                "West Lafayette",
                "Dallas",
                "Palmdale",
                "Keller",
                "New Braunfels",
                "Edinburg",
                "Charlotte",
                "Bellflower",
                "Baldwin Park",
                "New York City",
                "Porterville",
                "San Antonio",
                "Hollywood",
                "Virginia Beach",
                "Brooklyn",
                "Moreno Valley",
                "Brooklyn",
                "Fort Lauderdale",
                "Nashville",
                "Fairfield",
                "Bronx",
                "Brooklyn",
                "Frisco",
                "Bronx",
                "St. Peters",
                "Chicago",
                "Bronx",
                "Huntington Park",
                "Chula Vista",
                "Fremont",
                "Bronx",
                "Aurora",
                "Union City",
                "Ewa Beach",
                "Atlanta",
                "New York City",
                "Anaheim",
                "Houston",
                "Yuma",
                "Lancaster",
                "Aurora",
                "Beaverton",
                "Philadelphia",
                "Tulare",
                "Las Vegas",
                "Dallas",
                "Hollywood",
                "Hialeah",
                "Los Angeles",
                "Katy",
                "San Diego",
                "Waipahu",
                "Hollywood",
                "Corona",
                "Mansfield",
                "Phoenix",
                "Forest Hills",
                "Toa Baja",
                "Cumming",
                "Missouri City",
                "West Palm Beach",
                "Brooklyn",
                "Rancho Cucamonga",
                "Bronx",
                "San Francisco",
                "Pomona",
                "Beaverton",
                "Bakersfield",
                "Charlotte",
                "Leander",
                "Panorama City",
                "Chicago",
                "Simi Valley",
                "Las Vegas",
                "South Jordan",
                "Queen Creek",
                "Salt Lake City",
                "Allen",
                "Hamilton",
                "Toa Alta",
                "Bronx",
                "Woodbridge",
                "Tampa",
                "Laredo",
                "Chicago",
                "Silver Spring",
                "Port St. Lucie",
                "Waukegan",
                "Houston",
                "Denver",
                "Lynwood",
                "Burleson",
                "Yukon",
                "Chandler",
                "Philadelphia",
                "Powder Springs",
                "Redmond",
                "Lancaster",
                "El Cajon",
                "Passaic",
                "Winter Garden",
                "Stamford",
                "Chicago",
                "Brooklyn",
                "Washington",
                "Corona",
                "Bend",
                "Orlando",
                "Aurora",
                "Murrieta",
                "Portland",
                "Chicago",
                "Parker",
                "Cumming",
                "Santa Ana",
                "La Habra",
                "Vacaville",
                "Alpharetta",
                "Los Angeles",
                "San Diego",
                "Albuquerque",
                "San Jose",
                "Concord",
                "Duluth",
                "Miami",
                "Glendale",
                "Loganville",
                "San Bernardino",
                "Far Rockaway",
                "Wake Forest",
                "Stockbridge",
                "Bay Shore",
                "Parkville",
                "Napa",
                "Dallas",
                "Union City",
                "Lewisville",
                "Antioch",
                "Philadelphia",
                "Ypsilanti",
                "Bronx",
                "Mesa",
                "Huntington Station",
                "Brooklyn",
                "Washington",
                "North Las Vegas",
                "Chicago",
                "Douglasville",
                "Los Angeles",
                "Hanford",
                "South San Francisco",
                "Fremont",
                "Miami",
                "Bothell",
                "Weslaco",
                "Hialeah",
                "Brooklyn",
                "Los Angeles",
                "Roseville",
                "Tempe",
                "Humble",
                "North Hills",
                "Glendale",
                "Laredo",
                "Atlanta",
                "College Station",
                "Anaheim",
                "Clearfield",
                "Laguna Niguel",
                "San Jose",
                "Spring Valley",
                "Little Elm",
                "Hendersonville",
                "Elk Grove",
                "Lilburn",
                "Hayward",
                "Virginia Beach",
                "Elk Grove",
                "Marietta",
                "Indio",
                "Grove City",
                "Fort Worth",
                "Alpharetta",
                "Bayonne",
                "Daly City",
                "Jersey City",
                "New York City",
                "Chesapeake",
                "Woodstock",
                "Gilroy",
                "Phoenix",
                "Olathe",
                "Spring Valley",
                "Round Rock",
                "Brooklyn",
                "Philadelphia",
                "Los Angeles",
                "Lehi",
                "Salinas",
                "San Diego",
                "Brentwood",
                "Jamaica",
                "Jamaica",
                "San Pablo",
                "Murrieta",
                "Oviedo",
                "Chicago",
                "Stockton",
                "Lancaster",
                "Ithaca",
                "Ogden",
                "Wasilla",
                "Jacksonville",
                "West New York",
                "Meridian",
                "Albuquerque",
                "Ashburn",
                "Highland",
                "Washington",
                "Alameda",
                "Westerville",
                "Lake Worth",
                "Medina",
                "Chicago",
                "Brentwood",
                "Brockton",
                "Toms River",
                "Brooklyn",
                "Elyria",
                "Buckeye",
                "Bayamon",
                "New York City",
                "Greensboro",
                "Los Angeles",
                "Las Vegas",
                "Costa Mesa",
                "Las Vegas",
                "Mcallen",
                "Hilliard",
                "Gaithersburg",
                "Pico Rivera",
                "Berwyn",
                "San Bernardino",
                "El Monte",
                "National City",
                "Jackson Heights",
                "Fort Lauderdale",
                "Crown Point",
                "Montebello",
                "Rosemead",
                "Newark",
                "Broken Arrow",
                "Mission",
                "Garland",
                "Charlotte",
                "New York City",
                "Carmichael",
                "Brownsville",
                "Garland",
                "San Antonio",
                "Phoenix",
                "Richmond",
                "San Jose",
                "Huntington Beach",
                "San Antonio",
                "Phoenix",
                "San Francisco",
                "Philadelphia",
                "Azusa",
                "Jacksonville",
                "Austin",
                "Cupertino",
                "San Jose",
                "Columbia",
                "Hagerstown",
                "Bowling Green",
                "Orlando",
                "Ontario",
                "San Antonio",
                "San Antonio",
                "Bakersfield",
                "North Bergen",
                "Yonkers",
                "Clermont",
                "Round Lake",
                "Lancaster",
                "Spring",
                "Ontario",
                "Staten Island",
                "Taylor",
                "West Palm Beach",
                "Pompano Beach",
                "Orlando",
                "Chicago",
                "Miami",
                "Houston",
                "Germantown",
                "Pasadena",
                "Huntersville",
                "Malden",
                "Chicago",
                "San Antonio",
                "Lexington",
                "Vancouver",
                "Santa Ana",
                "Perris",
                "Hollywood",
                "Las Vegas",
                "Mesquite",
                "San Pedro",
                "The Colony",
                "Los Angeles",
                "Murfreesboro",
                "Salinas",
                "Austin",
                "Oceanside",
                "Fort Worth",
                "Simpsonville",
                "Bristol",
                "Baytown",
                "Mentor",
                "Arlington",
                "Summerville",
                "Milwaukee",
                "Richmond",
                "Colton",
                "Dallas",
                "Riverside",
                "Santa Clara",
                "Los Angeles",
                "Plymouth",
                "Newnan",
                "Lithonia",
                "El Cajon",
                "Medford",
                "Greeley",
                "Honolulu",
                "New Castle",
                "Phoenix",
                "El Paso",
                "Modesto",
                "Augusta",
                "Jamaica",
                "Houston",
                "New York City",
                "Bronx",
                "Los Angeles",
                "Waxhaw",
                "Acworth",
                "Smyrna",
                "Oklahoma City",
                "Tustin",
                "Bronx",
                "Lake Forest",
                "Jacksonville",
                "Annandale",
                "College Station",
                "Arecibo",
                "Goose Creek",
                "Fairfax",
                "Owings Mills",
                "Orlando",
                "Des Plaines",
                "Visalia",
                "Greenville",
                "Los Angeles",
                "Riverside",
                "Columbus",
                "San Antonio",
                "Miami",
                "Rock Hill",
                "Virginia Beach",
                "Franklin",
                "Virginia Beach",
                "Brandon",
                "Fayetteville",
                "Fredericksburg",
                "Savannah",
                "Kyle",
                "St. Paul",
                "Jonesboro",
                "Casa Grande",
                "Sacramento",
                "Jupiter",
                "Woodbridge",
                "Chicago",
                "Trujillo Alto",
                "New York City"],
    "fname": ["John",
                "William",
                "James",
                "Charles",
                "George",
                "Frank",
                "Joseph",
                "Thomas",
                "Henry",
                "Robert",
                "Edward",
                "Harry",
                "Walter",
                "Arthur",
                "Fred",
                "Albert",
                "Samuel",
                "David",
                "Louis",
                "Joe",
                "Charlie",
                "Clarence",
                "Richard",
                "Andrew",
                "Daniel",
                "Ernest",
                "Will",
                "Jesse",
                "Oscar",
                "Lewis",
                "Peter",
                "Benjamin",
                "Frederick",
                "Willie",
                "Alfred",
                "Sam",
                "Roy",
                "Herbert",
                "Jacob",
                "Tom",
                "Elmer",
                "Carl",
                "Lee",
                "Howard",
                "Martin",
                "Michael",
                "Bert",
                "Herman",
                "Jim",
                "Francis",
                "Harvey",
                "Earl",
                "Eugene",
                "Ralph",
                "Ed",
                "Claude",
                "Edwin",
                "Ben",
                "Charley",
                "Paul",
                "Edgar",
                "Isaac",
                "Otto",
                "Luther",
                "Lawrence",
                "Ira",
                "Patrick",
                "Guy",
                "Oliver",
                "Theodore",
                "Hugh",
                "Clyde",
                "Alexander",
                "August",
                "Floyd",
                "Homer",
                "Jack",
                "Leonard",
                "Horace",
                "Marion",
                "Philip",
                "Allen",
                "Archie",
                "Stephen",
                "Chester",
                "Willis",
                "Raymond",
                "Rufus",
                "Warren",
                "Jessie",
                "Milton",
                "Alex",
                "Leo",
                "Julius",
                "Ray",
                "Sidney",
                "Bernard",
                "Dan",
                "Jerry",
                "Calvin",
                "Perry",
                "Dave",
                "Anthony",
                "Eddie",
                "Amos",
                "Dennis",
                "Clifford",
                "Leroy",
                "Wesley",
                "Alonzo",
                "Garfield",
                "Franklin",
                "Emil",
                "Leon",
                "Nathan",
                "Harold",
                "Matthew",
                "Levi",
                "Moses",
                "Everett",
                "Lester",
                "Winfield",
                "Adam",
                "Lloyd",
                "Mack",
                "Fredrick",
                "Jay",
                "Jess",
                "Melvin",
                "Noah",
                "Aaron",
                "Alvin",
                "Norman",
                "Gilbert",
                "Elijah",
                "Victor",
                "Gus",
                "Nelson",
                "Jasper",
                "Silas",
                "Christopher",
                "Jake",
                "Mike",
                "Percy",
                "Adolph",
                "Maurice",
                "Cornelius",
                "Felix",
                "Reuben",
                "Wallace",
                "Claud",
                "Roscoe",
                "Sylvester",
                "Earnest",
                "Hiram",
                "Otis",
                "Simon",
                "Willard",
                "Irvin",
                "Mark",
                "Jose",
                "Wilbur",
                "Abraham",
                "Virgil",
                "Clinton",
                "Elbert",
                "Leslie",
                "Marshall",
                "Owen",
                "Wiley",
                "Anton",
                "Morris",
                "Manuel",
                "Phillip",
                "Augustus",
                "Emmett",
                "Eli",
                "Nicholas",
                "Wilson",
                "Alva",
                "Harley",
                "Newton",
                "Timothy",
                "Marvin",
                "Ross",
                "Curtis",
                "Edmund",
                "Jeff",
                "Elias",
                "Harrison",
                "Stanley",
                "Columbus",
                "Lon",
                "Ora",
                "Ollie",
                "Russell",
                "Pearl",
                "Solomon",
                "Arch",
                "Asa",
                "Clayton",
                "Enoch",
                "Irving",
                "Mathew",
                "Nathaniel",
                "Scott",
                "Hubert",
                "Lemuel",
                "Andy",
                "Ellis",
                "Emanuel",
                "Joshua",
                "Millard",
                "Vernon",
                "Wade",
                "Cyrus",
                "Miles",
                "Rudolph",
                "Sherman",
                "Austin",
                "Bill",
                "Chas",
                "Lonnie",
                "Monroe",
                "Byron",
                "Edd",
                "Emery",
                "Grant",
                "Jerome",
                "Max",
                "Mose",
                "Steve",
                "Gordon",
                "Abe",
                "Pete",
                "Chris",
                "Clark",
                "Gustave",
                "Orville",
                "Lorenzo",
                "Bruce",
                "Marcus",
                "Preston",
                "Bob",
                "Dock",
                "Donald",
                "Jackson",
                "Cecil",
                "Barney",
                "Jensen",
                "Yurem",
                "Mary",
                "Anna",
                "Emma",
                "Elizabeth",
                "Minnie",
                "Margaret",
                "Ida",
                "Alice",
                "Bertha",
                "Sarah",
                "Annie",
                "Clara",
                "Ella",
                "Florence",
                "Cora",
                "Martha",
                "Laura",
                "Nellie",
                "Grace",
                "Carrie",
                "Maude",
                "Mabel",
                "Bessie",
                "Jennie",
                "Gertrude",
                "Julia",
                "Hattie",
                "Edith",
                "Mattie",
                "Rose",
                "Catherine",
                "Lillian",
                "Ada",
                "Lillie",
                "Helen",
                "Jessie",
                "Louise",
                "Ethel",
                "Lula",
                "Myrtle",
                "Eva",
                "Frances",
                "Lena",
                "Lucy",
                "Edna",
                "Maggie",
                "Pearl",
                "Daisy",
                "Fannie",
                "Josephine",
                "Dora",
                "Rosa",
                "Katherine",
                "Agnes",
                "Marie",
                "Nora",
                "May",
                "Mamie",
                "Blanche",
                "Stella",
                "Ellen",
                "Nancy",
                "Effie",
                "Sallie",
                "Nettie",
                "Della",
                "Lizzie",
                "Flora",
                "Susie",
                "Maud",
                "Mae",
                "Etta",
                "Harriet",
                "Sadie",
                "Caroline",
                "Katie",
                "Lydia",
                "Elsie",
                "Kate",
                "Susan",
                "Mollie",
                "Alma",
                "Addie",
                "Georgia",
                "Eliza",
                "Lulu",
                "Nannie",
                "Lottie",
                "Amanda",
                "Belle",
                "Charlotte",
                "Rebecca",
                "Ruth",
                "Viola",
                "Olive",
                "Amelia",
                "Hannah",
                "Jane",
                "Virginia",
                "Emily",
                "Matilda",
                "Irene",
                "Kathryn",
                "Esther",
                "Willie",
                "Henrietta",
                "Ollie",
                "Amy",
                "Rachel",
                "Sara",
                "Estella",
                "Theresa",
                "Augusta",
                "Ora",
                "Pauline",
                "Josie",
                "Lola",
                "Sophia",
                "Leona",
                "Anne",
                "Mildred",
                "Ann",
                "Beulah",
                "Callie",
                "Lou",
                "Delia",
                "Eleanor",
                "Barbara",
                "Iva",
                "Louisa",
                "Maria",
                "Mayme",
                "Evelyn",
                "Estelle",
                "Nina",
                "Betty",
                "Marion",
                "Bettie",
                "Dorothy",
                "Luella",
                "Inez",
                "Lela",
                "Rosie",
                "Allie",
                "Millie",
                "Janie",
                "Cornelia",
                "Victoria",
                "Ruby",
                "Winifred",
                "Alta",
                "Celia",
                "Christine",
                "Beatrice",
                "Birdie",
                "Harriett",
                "Mable",
                "Myra",
                "Sophie",
                "Tillie",
                "Isabel",
                "Sylvia",
                "Carolyn",
                "Isabelle",
                "Leila",
                "Sally",
                "Ina",
                "Essie",
                "Bertie",
                "Nell",
                "Alberta",
                "Katharine",
                "Lora",
                "Rena",
                "Mina",
                "Rhoda",
                "Mathilda",
                "Abbie",
                "Eula",
                "Dollie",
                "Hettie",
                "Eunice",
                "Fanny",
                "Ola",
                "Lenora",
                "Adelaide",
                "Christina",
                "Lelia",
                "Nelle",
                "Sue",
                "Johanna",
                "Lilly",
                "Lucinda",
                "Minerva",
                "Lettie",
                "Roxie",
                "Cynthia",
                "Helena",
                "Hilda",
                "Hulda",
                "Bernice",
                "Genevieve",
                "Jean",
                "Cordelia",
                "Marian",
                "Francis",
                "Jeanette",
                "Adeline",
                "Gussie",
                "Leah",
                "Lois",
                "Lura",
                "Mittie",
                "Hallie",
                "Isabella",
                "Olga",
                "Phoebe",
                "Teresa",
                "Hester",
                "Lida",
                "Lina",
                "Marguerite",
                "Winnie",
                "Claudia",
                "Vera",
                "Cecelia",
                "Bess",
                "Emilie",
                "John",
                "Rosetta",
                "Verna",
                "Myrtie",
                "Cecilia",
                "Elva",
                "Olivia",
                "Ophelia",
                "Georgie",
                "Elnora",
                "Violet",
                "Adele",
                "Lily",
                "Linnie",
                "Loretta",
                "Madge",
                "Polly",
                "Virgie",
                "Eugenia",
                "Lucile"],
    "lname": ["Smith",
            "Johnson",
            "Williams",
            "Brown",
            "Jones",
            "Miller",
            "Davis",
            "Garcia",
            "Rodriguez",
            "Wilson",
            "Martinez",
            "Anderson",
            "Taylor",
            "Thomas",
            "Hernandez",
            "Moore",
            "Martin",
            "Jackson",
            "Thompson",
            "White",
            "Lopez",
            "Lee",
            "Gonzalez",
            "Harris",
            "Clark",
            "Lewis",
            "Robinson",
            "Walker",
            "Perez",
            "Hall",
            "Young",
            "Allen",
            "Sanchez",
            "Wright",
            "King",
            "Scott",
            "Green",
            "Baker",
            "Adams",
            "Nelson",
            "Hill",
            "Ramirez",
            "Campbell",
            "Mitchell",
            "Roberts",
            "Carter",
            "Phillips",
            "Evans",
            "Turner",
            "Torres",
            "Parker",
            "Collins",
            "Edwards",
            "Stewart",
            "Flores",
            "Morris",
            "Nguyen",
            "Murphy",
            "Rivera",
            "Cook",
            "Rogers",
            "Morgan",
            "Peterson",
            "Cooper",
            "Reed",
            "Bailey",
            "Bell",
            "Gomez",
            "Kelly",
            "Howard",
            "Ward",
            "Cox",
            "Diaz",
            "Richardson",
            "Wood",
            "Watson",
            "Brooks",
            "Bennett",
            "Gray",
            "James",
            "Reyes",
            "Cruz",
            "Hughes",
            "Price",
            "Myers",
            "Long",
            "Foster",
            "Sanders",
            "Ross",
            "Morales",
            "Powell",
            "Sullivan",
            "Russell",
            "Ortiz",
            "Jenkins",
            "Gutierrez",
            "Perry",
            "Butler",
            "Barnes",
            "Fisher",
            "Henderson",
            "Coleman",
            "Simmons",
            "Patterson",
            "Jordan",
            "Reynolds",
            "Hamilton",
            "Graham",
            "Kim",
            "Gonzales",
            "Alexander",
            "Ramos",
            "Wallace",
            "Griffin",
            "West",
            "Cole",
            "Hayes",
            "Chavez",
            "Gibson",
            "Bryant",
            "Ellis",
            "Stevens",
            "Murray",
            "Ford",
            "Marshall",
            "Owens",
            "Mcdonald",
            "Harrison",
            "Ruiz",
            "Kennedy",
            "Wells",
            "Alvarez",
            "Woods",
            "Mendoza",
            "Castillo",
            "Olson",
            "Webb",
            "Washington",
            "Tucker",
            "Freeman",
            "Burns",
            "Henry",
            "Vasquez",
            "Snyder",
            "Simpson",
            "Crawford",
            "Jimenez",
            "Porter",
            "Mason",
            "Shaw",
            "Gordon",
            "Wagner",
            "Hunter",
            "Romero",
            "Hicks",
            "Dixon",
            "Hunt",
            "Palmer",
            "Robertson",
            "Black",
            "Holmes",
            "Stone",
            "Meyer",
            "Boyd",
            "Mills",
            "Warren",
            "Fox",
            "Rose",
            "Rice",
            "Moreno",
            "Schmidt",
            "Patel",
            "Ferguson",
            "Nichols",
            "Herrera",
            "Medina",
            "Ryan",
            "Fernandez",
            "Weaver",
            "Daniels",
            "Stephens",
            "Gardner",
            "Payne",
            "Kelley",
            "Dunn",
            "Pierce",
            "Arnold",
            "Tran",
            "Spencer",
            "Peters",
            "Hawkins",
            "Grant",
            "Hansen",
            "Castro",
            "Hoffman",
            "Hart",
            "Elliott",
            "Cunningham",
            "Knight",
            "Bradley",
            "Carroll",
            "Hudson",
            "Duncan",
            "Armstrong",
            "Berry",
            "Andrews",
            "Johnston",
            "Ray",
            "Lane",
            "Riley",
            "Carpenter",
            "Perkins",
            "Aguilar",
            "Silva",
            "Richards",
            "Willis",
            "Matthews",
            "Chapman",
            "Lawrence",
            "Garza",
            "Vargas",
            "Watkins",
            "Wheeler",
            "Larson",
            "Carlson",
            "Harper",
            "George",
            "Greene",
            "Burke",
            "Guzman",
            "Morrison",
            "Munoz",
            "Jacobs",
            "Obrien",
            "Lawson",
            "Franklin",
            "Lynch",
            "Bishop",
            "Carr",
            "Salazar",
            "Austin",
            "Mendez",
            "Gilbert",
            "Jensen",
            "Williamson",
            "Montgomery",
            "Harvey",
            "Oliver",
            "Howell",
            "Dean",
            "Hanson",
            "Weber",
            "Garrett",
            "Sims",
            "Burton",
            "Fuller",
            "Soto",
            "Mccoy",
            "Welch",
            "Chen",
            "Schultz",
            "Walters",
            "Reid",
            "Fields",
            "Walsh",
            "Little",
            "Fowler",
            "Bowman",
            "Davidson",
            "May",
            "Day",
            "Schneider",
            "Newman",
            "Brewer",
            "Lucas",
            "Holland",
            "Wong",
            "Banks",
            "Santos",
            "Curtis",
            "Pearson",
            "Delgado",
            "Valdez",
            "Pena",
            "Rios",
            "Douglas",
            "Sandoval",
            "Barrett",
            "Hopkins",
            "Keller",
            "Guerrero",
            "Stanley",
            "Bates",
            "Alvarado",
            "Beck",
            "Ortega",
            "Wade",
            "Estrada",
            "Contreras",
            "Barnett",
            "Caldwell",
            "Santiago",
            "Lambert",
            "Powers",
            "Chambers",
            "Nunez",
            "Craig",
            "Leonard",
            "Lowe",
            "Rhodes",
            "Byrd",
            "Gregory",
            "Shelton",
            "Frazier",
            "Becker",
            "Maldonado",
            "Fleming",
            "Vega",
            "Sutton",
            "Cohen",
            "Jennings",
            "Parks",
            "Mcdaniel",
            "Watts",
            "Barker",
            "Norris",
            "Vaughn",
            "Vazquez",
            "Holt",
            "Schwartz",
            "Steele",
            "Benson",
            "Neal",
            "Dominguez",
            "Horton",
            "Terry",
            "Wolfe",
            "Hale",
            "Lyons",
            "Graves",
            "Haynes",
            "Miles",
            "Park",
            "Warner",
            "Padilla",
            "Bush",
            "Thornton",
            "Mccarthy",
            "Mann",
            "Zimmerman",
            "Erickson",
            "Fletcher",
            "Mckinney",
            "Page",
            "Dawson",
            "Joseph",
            "Marquez",
            "Reeves",
            "Klein",
            "Espinoza",
            "Baldwin",
            "Moran",
            "Love",
            "Robbins",
            "Higgins",
            "Ball",
            "Cortez",
            "Le",
            "Griffith",
            "Bowen",
            "Sharp",
            "Cummings",
            "Ramsey",
            "Hardy",
            "Swanson",
            "Barber",
            "Acosta",
            "Luna",
            "Chandler",
            "Blair",
            "Daniel",
            "Cross",
            "Simon",
            "Dennis",
            "Oconnor",
            "Quinn",
            "Gross",
            "Navarro",
            "Moss",
            "Fitzgerald",
            "Doyle",
            "Mclaughlin",
            "Rojas",
            "Rodgers",
            "Stevenson",
            "Singh",
            "Yang",
            "Figueroa",
            "Harmon",
            "Newton",
            "Paul",
            "Manning",
            "Garner",
            "Mcgee",
            "Reese",
            "Francis",
            "Burgess",
            "Adkins",
            "Goodman",
            "Curry",
            "Brady",
            "Christensen",
            "Potter",
            "Walton",
            "Goodwin",
            "Mullins",
            "Molina",
            "Webster",
            "Fischer",
            "Campos",
            "Avila",
            "Sherman",
            "Todd",
            "Chang",
            "Blake",
            "Malone",
            "Wolf",
            "Hodges",
            "Juarez",
            "Gill",
            "Farmer",
            "Hines",
            "Gallagher",
            "Duran",
            "Hubbard",
            "Cannon",
            "Miranda",
            "Wang",
            "Saunders",
            "Tate",
            "Mack",
            "Hammond",
            "Carrillo",
            "Townsend",
            "Wise",
            "Ingram",
            "Barton",
            "Mejia",
            "Ayala",
            "Schroeder",
            "Hampton",
            "Rowe",
            "Parsons",
            "Frank",
            "Waters",
            "Strickland",
            "Osborne",
            "Maxwell",
            "Chan",
            "Deleon",
            "Norman",
            "Harrington",
            "Casey",
            "Patton",
            "Logan",
            "Bowers",
            "Mueller",
            "Glover",
            "Floyd",
            "Hartman",
            "Buchanan",
            "Cobb",
            "French",
            "Kramer",
            "Mccormick",
            "Clarke",
            "Tyler",
            "Gibbs",
            "Moody",
            "Conner",
            "Sparks",
            "Mcguire",
            "Leon",
            "Bauer",
            "Norton",
            "Pope",
            "Flynn",
            "Hogan",
            "Robles",
            "Salinas",
            "Yates",
            "Lindsey",
            "Lloyd",
            "Marsh",
            "Mcbride",
            "Owen",
            "Solis",
            "Pham",
            "Lang",
            "Pratt"],
    "months": ["January", "February", "March", "April", "May", 
               "June", "July", "August", "September", "October",
               "November", "December"],
    "college": ["Alabama A&M University",
                "Alabama State University",
                "Athens State University",
                "Auburn University",
                "Auburn University At Montgomery",
                "Bevill State Community College",
                "Birmingham-Southern College",
                "Calhoun Community College",
                "Central Alabama Community College",
                "Enterprise State Community College",
                "Gadsden State Community College",
                "Huntingdon College",
                "Jacksonville State University",
                "Lurleen B. Wallace Community College",
                "Marion Military Institute",
                "Miles College",
                "Samford University",
                "Snead State Community College",
                "Southern Union State Community College",
                "Spring Hill College",
                "Troy University",
                "Troy University Dothan",
                "Troy University Montgomery",
                "Troy University Phenix City",
                "Tuskegee University",
                "University Of Alabama",
                "University Of Alabama At Birmingham",
                "University Of Alabama In Huntsville",
                "University Of Montevallo",
                "University Of North Alabama",
                "University Of South Alabama",
                "University Of West Alabama",
                "Ilisagvik College",
                "University Of Alaska Anchorage",
                "University Of Alaska Fairbanks",
                "University Of Alaska Southeast",
                "American Samoa Community College",
                "Arizona State University",
                "Arizona Western College",
                "Dine College",
                "Embry-Riddle Aeronautical University At Prescott",
                "Grand Canyon University",
                "Midwestern University At Glendale",
                "Mohave Community College",
                "Northern Arizona University",
                "University Of Arizona",
                "Arkansas Northeastern College",
                "Arkansas State University",
                "Arkansas State University-Newport",
                "Arkansas Tech University",
                "Black River Technical College",
                "Central Baptist College",
                "Cossatot Community College Of The University Of Arkansas",
                "Harding University",
                "Henderson State University",
                "Hendrix College",
                "John Brown University",
                "Lyon College",
                "National Park College",
                "North Arkansas College",
                "Northwest Arkansas Community College",
                "Ouachita Baptist University",
                "South Arkansas Community College",
                "Southern Arkansas University",
                "University Of Arkansas",
                "University Of Arkansas Community College Rich Mountain",
                "University Of Arkansas Community College At Morrilton",
                "University Of Arkansas Hope-Texarkana",
                "University Of Arkansas At Fort Smith",
                "University Of Arkansas At Little Rock",
                "University Of Arkansas At Monticello",
                "University Of Arkansas At Pine Bluff",
                "University Of Arkansas For Medical Sciences",
                "University Of Arkansas-Pulaski Technical College",
                "University Of Central Arkansas",
                "University Of The Ozarks",
                "Academy Of Art University",
                "Antelope Valley College",
                "Azusa Pacific University",
                "Bakersfield College",
                "Biola University",
                "California Baptist University",
                "California Institute Of Technology",
                "California Lutheran University",
                "California Polytechnic State University, San Luis Obispo",
                "California State Polytechnic University, Pomona",
                "California State University Maritime Academy",
                "California State University, Bakersfield",
                "California State University, Channel Islands",
                "California State University, Chico",
                "California State University, Dominguez Hills",
                "California State University, East Bay",
                "California State University, Fullerton",
                "California State University, Long Beach",
                "California State University, Los Angeles",
                "California State University, Monterey Bay",
                "California State University, Northridge",
                "California State University, Sacramento",
                "California State University, San Bernardino",
                "California State University, San Marcos",
                "California State University, Stanislaus",
                "Chapman University",
                "Claremont Mckenna College",
                "Concordia University Irvine",
                "Cypress College",
                "Dominican University Of California",
                "El Camino Community College",
                "Feather River College",
                "Foothill College",
                "Fresno Pacific University",
                "Fresno State University",
                "Harvey Mudd College",
                "Holy Names University",
                "Humboldt State University",
                "Los Angeles Community College District",
                "Loyola Marymount University",
                "Menlo College",
                "Mills College",
                "Miracosta College",
                "Modesto Junior College",
                "Naval Postgraduate School",
                "Notre Dame De Namur University",
                "Occidental College",
                "Pepperdine University",
                "Pitzer College",
                "Point Loma Nazarene University",
                "Pomona College",
                "Rio Hondo College",
                "Saint Mary'S College Of California",
                "San Diego City College",
                "San Diego Mesa College",
                "San Diego Miramar College",
                "San Diego State University System",
                "San Francisco State University",
                "San Jose State University",
                "Santa Ana College",
                "Santa Clara University",
                "Santa Monica College",
                "Santiago Canyon College",
                "Scripps College",
                "Shasta College",
                "Skyline College",
                "Solano Community College",
                "Sonoma State University",
                "Southwestern College",
                "Stanford University",
                "Teachers College Of San Joaquin",
                "University Of California, Berkeley",
                "University Of California, Davis",
                "University Of California, Hastings College Of Law",
                "University Of California, Irvine",
                "University Of California, Los Angeles",
                "University Of California, Merced",
                "University Of California, Riverside",
                "University Of California, San Diego",
                "University Of California, San Francisco",
                "University Of California, Santa Barbara",
                "University Of California, Santa Cruz",
                "University Of La Verne",
                "University Of Redlands",
                "University Of San Diego",
                "University Of San Francisco",
                "University Of Southern California",
                "University Of The Pacific",
                "Westmont College",
                "Whittier College",
                "Adams State University",
                "Arapahoe Community College",
                "Colorado Christian University",
                "Colorado College",
                "Colorado Mesa University",
                "Colorado Mountain College Glenwood Springs",
                "Colorado School Of Mines",
                "Colorado State University",
                "Colorado State University-Pueblo",
                "Community College Of Aurora",
                "Community College Of Denver",
                "Fort Lewis College",
                "Front Range Community College",
                "Johnson & Wales University-Denver",
                "Lamar Community College",
                "Metropolitan State University Of Denver",
                "Morgan Community College",
                "Northeastern Junior College",
                "Otero Junior College",
                "Pikes Peak Community College",
                "Pueblo Community College",
                "Red Rocks Community College",
                "Regis University",
                "Trinidad State Junior College",
                "United States Air Force Academy",
                "University Of Colorado Boulder",
                "University Of Colorado Colorado Springs",
                "University Of Colorado Denver And Anschutz Medical Campus",
                "University Of Denver",
                "University Of Northern Colorado",
                "Western Colorado University",
                "Albertus Magnus College",
                "Central Connecticut State University",
                "Connecticut College",
                "Eastern Connecticut State University",
                "Fairfield University",
                "Mitchell College",
                "Post University",
                "Quinnipiac University",
                "Sacred Heart University",
                "Southern Connecticut State University",
                "Trinity College",
                "Tunxis Community College",
                "United States Coast Guard Academy",
                "University Of Bridgeport",
                "University Of Connecticut",
                "University Of Hartford",
                "University Of New Haven",
                "University Of Saint Joseph",
                "Wesleyan University",
                "Western Connecticut State University",
                "Yale University",
                "Delaware State University",
                "Delaware Technical Community College Dover ",
                "Delaware Technical Community College Georgetown",
                "Delaware Technical Community College Stanton",
                "Goldey-Beacom College",
                "University Of Delaware",
                "Wesley College",
                "Wilmington University",
                "Adventhealth University",
                "American Institute Of Beauty",
                "Atlantic Technical College",
                "Atlantis University",
                "Ave Maria University",
                "Aveda Institute-South Florida",
                "Aveda Institute-Tallahassee",
                "Aviation Institute Of Maintenance-Orlando",
                "Barry University",
                "Bene'S Career Academy",
                "Bethune-Cookman University",
                "Big Bend Technical College",
                "Broward College",
                "Charlotte Technical College",
                "Chipola College",
                "City College At Gainesville",
                "College Of Central Florida",
                "Concorde Career Institute-Miramar",
                "Cortiva Institute-Maitland",
                "Daytona State College",
                "Eastern Florida State College",
                "Eckerd College",
                "Edward Waters College",
                "Embry-Riddle Aeronautical University At Daytona Beach",
                "Erwin Technical College",
                "Everglades University",
                "First Coast Technical College",
                "Flagler College",
                "Flagler Technical College",
                "Florida A&M University",
                "Florida Atlantic University",
                "Florida Career College At Tampa",
                "Florida College",
                "Florida Gateway College",
                "Florida Gulf Coast University",
                "Florida Institute Of Recording Sound And Technology",
                "Florida Institute Of Technology",
                "Florida International University",
                "Florida Memorial University",
                "Florida National University",
                "Florida Polytechnic University",
                "Florida Southwestern State College",
                "Florida Southern College",
                "Florida State College At Jacksonville",
                "Florida State University",
                "Florida Technical College",
                "Fort Myers Technical College",
                "Fortis Institute At Port Saint Lucie",
                "Fred K. Marchman Technical College",
                "Full Sail University",
                "Gadsden Technical Institute",
                "George Stone Technical College",
                "Gulf Coast State College",
                "Gwinnett Institute",
                "Hci College",
                "Hci College At Fort Lauderdale",
                "Hillsborough Community College",
                "Immokalee Technical College",
                "Indian River State College",
                "Jacksonville University",
                "Johnson & Wales University-North Miami",
                "Keiser University Flagship",
                "Keiser University At Fort Myers",
                "Keiser University At Jacksonville",
                "Keiser University At Lakeland",
                "Keiser University At Melbourne",
                "Keiser University At Sarasota",
                "Keiser University At Tallahassee",
                "Keiser University At West Palm Beach",
                "Keiser University-Daytona",
                "Keiser University-Port St Lucie",
                "Lake Technical College",
                "Lake-Sumter State College",
                "Lindsey Hopkins Technical College",
                "Lively Technical College",
                "Loraines Academy & Spa",
                "Lorenzo Walker Technical College",
                "Lynn University",
                "Marion Technical College",
                "Meridian College",
                "Miami Dade College",
                "Miami International University Of Art And Design",
                "New College Of Florida",
                "North Florida College",
                "Northwest Florida State College",
                "Nouvelle Institute",
                "Nova Southeastern University",
                "Okaloosa Technical College",
                "Orange Technical College Mid Florida Campus",
                "Orange Technical College Orlando Campus",
                "Orange Technical College Westside Campus",
                "Orange Technical College Winter Park Campus",
                "Palm Beach Atlantic University",
                "Palm Beach State College",
                "Pasco-Hernando State College",
                "Paul Mitchell The School-Jacksonville",
                "Pensacola State College",
                "Pinellas Technical College-St. Petersburg",
                "Polk State College",
                "Praxis Institute",
                "Radford M Locklin Technical College",
                "Rasmussen College At Fort Myers",
                "Ridge Technical College",
                "Riveroak Technical College",
                "Rollins College",
                "Saint Leo University",
                "Santa Fe College",
                "Seminole State College Of Florida",
                "Sheridan Technical College",
                "South Florida Bible College And Theological Seminary",
                "South Florida State College",
                "Southeastern College At West Palm Beach",
                "Southeastern University",
                "St. Johns River State College",
                "St. Petersburg College",
                "St. Thomas University",
                "State College Of Florida, Manatee-Sarasota",
                "Stetson University",
                "Strayer University At Fort Lauderdale",
                "Suncoast Technical College",
                "Sunstate Academy-Jones Technical Institute",
                "Tallahassee Community College",
                "The College Of The Florida Keys",
                "Traviss Technical College",
                "Trinity College Of Florida",
                "Universal Technical Institute Orlando",
                "University Of Central Florida",
                "University Of Florida",
                "University Of Fort Lauderdale",
                "University Of Miami",
                "University Of North Florida",
                "University Of South Florida",
                "University Of South Florida Sarasota-Manatee ",
                "University Of South Florida St. Petersburg",
                "University Of Tampa",
                "University Of West Florida",
                "Valencia College",
                "Warner University",
                "Webber International University",
                "William T. Mcfatter Technical College",
                "Withlacoochee Technical College",
                "Abraham Baldwin Agricultural College",
                "Agnes Scott College",
                "Albany State University",
                "Atlanta Metropolitan State College",
                "Augusta University",
                "Berry College",
                "Brenau University",
                "Clark Atlanta University",
                "Clayton State University",
                "College Of Coastal Georgia",
                "Columbus State University",
                "Covenant College",
                "Dalton State College",
                "East Georgia State College",
                "Emmanuel College",
                "Emory University",
                "Fort Valley State University",
                "Georgia College & State University",
                "Georgia Gwinnett College",
                "Georgia Highlands College",
                "Georgia Institute Of Technology",
                "Georgia Military College",
                "Georgia Southern University",
                "Georgia Southwestern State University",
                "Georgia State University",
                "Gordon State College",
                "Kennesaw State University",
                "Lagrange College",
                "Mercer University",
                "Middle Georgia State University",
                "Morehouse College",
                "Oglethorpe University",
                "Piedmont College",
                "Savannah State University",
                "Shorter University",
                "South Georgia State College",
                "University Of Georgia",
                "University Of North Georgia",
                "University Of West Georgia",
                "Valdosta State University",
                "Wesleyan College",
                "Young Harris College",
                "University Of Guam",
                "Brigham Young University-Hawaii",
                "Chaminade University Of Honolulu",
                "Hawaii Pacific University",
                "Kapiolani Community College",
                "Leeward Community College",
                "University Of Hawaii Maui College",
                "University Of Hawaii At Hilo",
                "University Of Hawaii At Manoa",
                "University Of Hawaii-West Oahu",
                "Boise State University",
                "Brigham Young University-Idaho",
                "College Of Idaho ",
                "College Of Southern Idaho",
                "Idaho State University",
                "Lewis-Clark State College",
                "North Idaho College",
                "Northwest Nazarene University",
                "University Of Idaho",
                "Augustana College",
                "Aurora University",
                "Benedictine University",
                "Blackburn College",
                "Bradley University",
                "Chicago State University",
                "Columbia College Chicago",
                "Concordia University Chicago",
                "Depaul University",
                "Dominican University",
                "Eastern Illinois University",
                "Elmhurst University",
                "Eureka College",
                "Governors State University",
                "Greenville University",
                "Illinois College",
                "Illinois Institute Of Technology",
                "Illinois State University",
                "Illinois Wesleyan University",
                "Kaskaskia College",
                "Knox College",
                "Lake Forest College",
                "Lake Land College",
                "Lewis University",
                "Loyola University Chicago",
                "Mckendree University",
                "Midwestern University At Downers Grove",
                "Millikin University",
                "Monmouth College",
                "Moody Bible Institute",
                "North Central College",
                "North Park University",
                "Northeastern Illinois University",
                "Northern Illinois University ",
                "Northwestern University",
                "Olivet Nazarene University",
                "Parkland College",
                "Principia College",
                "Quincy University",
                "Rockford University",
                "Saint Xavier University",
                "School Of The Art Institute Of Chicago",
                "Southeastern Illinois College",
                "Southern Illinois University Carbondale",
                "Southern Illinois University Edwardsville",
                "Southwestern Illinois College",
                "University Of Chicago",
                "University Of Illinois Springfield",
                "University Of Illinois Urbana-Champaign",
                "University Of Illinois At Chicago",
                "Western Illinois University",
                "Wheaton College",
                "Anderson University",
                "Ball State University",
                "Butler University",
                "Depauw University",
                "Earlham College",
                "Franklin College",
                "Goshen College",
                "Grace College And Theological Seminary",
                "Hanover College",
                "Indiana State University",
                "Indiana University Bloomington",
                "Indiana University East",
                "Indiana University Kokomo",
                "Indiana University Northwest",
                "Indiana University South Bend",
                "Indiana University Southeast",
                "Indiana University-Purdue University Indianapolis",
                "Ivy Tech Community College System",
                "Manchester University",
                "Marian University"],
    "interest": ["Sports", "Fashion","Fitness","Gaming","Reading","Nature","Cooking", "Travel"]
    
}

def email_gen(fname, lname):
    unique=fname[0].lower()+lname.lower()
    return unique+"@gmail.com"
def gen_random_person_txt(f):
    last_name=random_samples['lname'][random.randrange(499)]
    first_name=random_samples['fname'][random.randrange(499)]
    f.write(last_name+", " + first_name + "\n")
    age=random.randrange(18,60)
    mInd=random.randrange(11)
    month=random_samples['months'][mInd]
    if (month=="February"):
        day=random.randrange(1,28)
    elif (month=="April" or month=="June" or month=="September" or month=="November"):
        day=random.randrange(1,30)
    else:
        day=random.randrange(1,31)
    if (mInd>4):
        year=2022-age-1
    else:
        year=2022-age
    f.write(str(mInd)+"/"+str(day)+"/"+str(year)+"\n")
    f.write("(Home) " + email_gen(first_name, last_name) + "\n")
    f.write("(Cell) " + str(random.randrange(100,999))+str(random.randrange(100,999))+ str(random.randrange(1000,9999)) + "\n")
    f.write(str(age) + "\n")
    loc=random.randrange(0,499)
    f.write(random_samples['college'][loc]+"\n")
    f.write(random_samples['zips'][loc]+"\n")
    f.write(random_samples["interest"][random.randrange(7)]+"\n")
    f.write("------------------------------\n")

print("Enter the number of random people to generate: ")
x=input()
x=int(x)
f=open('dataset.txt','w')
for i in range(x):
    gen_random_person_txt(f)